### ISSUE TITLE
ALREADY SAVED DATA

### ISSUE THREAD

**Issue by Navlmao** [19Phin/Multiccount#2]
ALL MY SURVIVAL DATA HAS JUST BEEN GRIEFED HOW DO I GET IT BACK I HAD FULL NETHERITE AND ALL SORTS

**Comment by DialingSpoon527** [comment]
Calm down, DO NOT reopen world if you haven't already, and I'm going to need more information.

**Comment by DialingSpoon527** [comment]
Describe what you did leading up to it.
What version?
What account?
Singleplayer or multiplayer?
Do you have any backups?
Any other mods installed?

**Comment by Navlmao** [comment]
1.20.1
my own account?
singleplayer with essentials mod
no backups
mods like sodium and falling tree mod

**Comment by DialingSpoon527** [comment]
Can you send me world file?

**Comment by Navlmao** [comment]
it wont let me
but i put it in a google drive
https://drive.google.com/drive/folders/14_NhM1h9HZxbMov7-uIgfGxfpAmISCf9?usp=sharing

**Comment by DialingSpoon527** [comment]
Unfortunately there's no data for anyone with netherite. There is one for a player with some diamond tools and iron armor but that's it.

**Comment by DialingSpoon527** [comment]
There were 2 players on this world, did you change instances, was this a server or a lan world at one point?

**Comment by DialingSpoon527** [comment]
@Navlmao do you not realize I reply, or are you just busy

**Comment by Navlmao** [comment]
I didn't realize you replied. Yes my world was lan but it was through the essentials mod. My player data (stats and inventory items all of that) was gone.

**Comment by DialingSpoon527** [comment]
@Navlmao so I'm sorry, not much I can do, I would like to know more about the encounter though

**Comment by DialingSpoon527** [comment]
Did the multicount ever function properly?
Did you use multiplayer while you had multicount? 
was multiplayer used before/after the error?

**Comment by Navlmao** [comment]
I didn't use multiplayer with multicount and multiplayer was used before, using the mod and joining my world got rid of the save file
